#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

create_folder:
  path: /create_folder
  methods: 'POST'
  controller: App\Controller\CreateFolderController::mkdir

download:
  path: /download/{base}/{filename}
  controller: App\Controller\DownloadController::index
  requirements:
      base: .+
      filename: .*

images:
  path: /images
  controller: App\Controller\ImageViewController::index

images_view:
  path: /images/{year}/{month}
  controller: App\Controller\ImageViewController::view
  requirements:
      year: .+
      month: .+

delete:
  path: /delete/{filename}
  controller: App\Controller\DeleteController::index
  requirements:
      filename: .+

upload:
  path: /upload
  controller: App\Controller\UploadController::index

create:
  path: /create
  controller: App\Controller\CreateFolderController::create

youtube_dl:
  path: /tools/youtube
  controller: App\Controller\YouTubeController::index