#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

create_folder:
  path: /create_folder
  methods: 'POST'
  controller: App\Controller\CreateFolderController::mkdir

download:
  path: /download/{base}/{filename}
  controller: App\Controller\DownloadController::index
  requirements:
      base: .+
      filename: .*

images:
  path: /images
  controller: App\Controller\ImageViewController::index

tag_view:
  path: /images/tag_view/{index}
  controller: App\Controller\EsController::tagView

upload:
  path: /upload
  controller: App\Controller\UploadController::index

create:
  path: /create
  controller: App\Controller\CreateFolderController::create

car_view:
  path: /car/overview
  controller: App\Controller\CarController::overview

car_data:
  path: /car/data
  controller: App\Controller\CarController::data

send_to_dropbox:
  path: /send_to_dropbox
  controller: App\Controller\ImageViewController::sendToDrop

youtube_dl:
  path: /music/youtube
  controller: App\Controller\YouTubeController::index