# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    env(ALLOCINE_PARTNER): '100043982026'
    env(ALLOCINE_SECRET): '29d185d98c984a359e6e6f26a0474269'
    env(PWD): '1234'
    locale: 'en'
    image_exclude_folder: "Dropbox|TEMP|creche|logo|_thumbnails"
    image_target: "/home/ansaoo/Images"
    image_root: "/home/ansaoo/Images"
    image_thumb: "/home/ansaoo/Images/_thumbnails"
    scan_target: "%kernel.project_dir%/public/scans"
    upload_allowed: "jpg|jpeg|mov|mts|mp4"
    upload_target: "%kernel.project_dir%/public/upload"
    upload_tmp_path: "%kernel.project_dir%/public/upload/tmp"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Services\Allocine:
        arguments:
            $partner_key: '%env(ALLOCINE_PARTNER)%'
            $secret_key: '%env(ALLOCINE_SECRET)%'

    App\Services\FileUploader:
        arguments:
            $targetDir: '%upload_tmp_path%'

    App\Services\PictureManager:
        arguments:
            $em: '@doctrine.orm.entity_manager'
            $excludeFolder: "%image_exclude_folder%"
            $rootFolder: "%image_root%"
            $scanHistoryFolder: "%scan_target%"
